# Generated by Django 4.2.10 on 2024-03-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customimage", "0002_initial"),
        ("sitesettings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to="customimage.customimage",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand logo used in the navbar and throughout the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customimage.customimage",
                verbose_name="Logo",
            ),
        ),
    ]
