# Generated by Django 4.2.9 on 2024-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LongEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=100)),
                (
                    "province_id",
                    models.CharField(choices=[("PV28", "Zuid-Holland")], max_length=20),
                ),
                (
                    "region_id",
                    models.CharField(
                        choices=[
                            ("REG03", "Drechsteden"),
                            ("REG05", "Haaglanden"),
                            ("REG01", "Holland Rijnland"),
                            ("REG02", "Midden-Holland"),
                            ("REG04", "Rotterdam"),
                            ("REG06", "Zuid-Hollandse Eilanden"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "municipality_id",
                    models.CharField(
                        choices=[
                            ("GM0482", "Alblasserdam"),
                            ("GM0484", "Alphen aan den Rijn"),
                            ("GM0489", "Barendrecht"),
                            ("GM0501", "Brielle"),
                            ("GM0502", "Capelle aan den IJssel"),
                            ("GM0503", "Delft"),
                            ("GM0505", "Dordrecht"),
                            ("GM0512", "Gorinchem"),
                            ("GM0513", "Gouda"),
                            ("GM0518", "'s-Gravenhage'"),
                            ("GM0523", "Hardinxveld-Giessendam"),
                            ("GM0530", "Hellevoetsluis"),
                            ("GM0531", "Hendrik-Ido-Ambacht"),
                            ("GM0534", "Hillegom"),
                            ("GM0537", "Katwijk"),
                            ("GM0542", "Krimpen aan den IJssel"),
                            ("GM0546", "Leiden"),
                            ("GM0547", "Leiderdorp"),
                            ("GM0553", "Lisse"),
                            ("GM0556", "Maassluis"),
                            ("GM0569", "Nieuwkoop"),
                            ("GM0575", "Noordwijk"),
                            ("GM0579", "Oegstgeest"),
                            ("GM0590", "Papendrecht"),
                            ("GM0597", "Ridderkerk"),
                            ("GM0599", "Rotterdam"),
                            ("GM0603", "Rijswijk"),
                            ("GM0606", "Schiedam"),
                            ("GM0610", "Sliedrecht"),
                            ("GM0613", "Albrandswaard"),
                            ("GM0614", "Westvoorne"),
                            ("GM0622", "Vlaardingen"),
                            ("GM0626", "Voorschoten"),
                            ("GM0627", "Waddinxveen"),
                            ("GM0629", "Wassenaar"),
                            ("GM0637", "Zoetermeer"),
                            ("GM0638", "Zoeterwoude"),
                            ("GM0642", "Zwijndrecht"),
                            ("GM1525", "Teylingen"),
                            ("GM1621", "Lansingerland"),
                            ("GM1783", "Westland"),
                            ("GM1842", "Midden-Delfland"),
                            ("GM1884", "Kaag en Braassem"),
                            ("GM1892", "Zuidplas"),
                            ("GM1901", "Bodegraven-Reeuwijk"),
                            ("GM1916", "Leidschendam-Voorburg"),
                            ("GM1924", "Goeree-Overflakkee"),
                            ("GM1926", "Pijnacker-Nootdorp"),
                            ("GM1930", "Nissewaard"),
                            ("GM1931", "Krimpenerwaard"),
                            ("GM1963", "Hoeksche Waard"),
                            ("GM1978", "Molenlanden"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uuid", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=100)),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("Electricity", "Electriciteit"),
                            ("Hydrogen", "Waterstof"),
                            ("Methane", "Methaan"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Curtailment", "Curtailment"),
                            ("Demand", "Demand"),
                            ("Process_flex", "Process Flex"),
                            ("Supply", "Supply"),
                            ("System_flex", "System Flex"),
                            ("Exchange", "Exchange"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sector", models.CharField(max_length=100)),
            ],
        ),
    ]
