# Generated by Django 4.2.9 on 2024-02-13 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LongEntry",
            new_name="EnergyUnit",
        ),
    ]
