# Generated by Django 4.2.9 on 2024-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0002_rename_longentry_energyunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyunit",
            name="value",
            field=models.FloatField(),
        ),
    ]
