# Generated by Django 4.2.9 on 2024-02-26 08:23

from django.db import migrations
from django.db.migrations.operations import RunPython
from pathlib import Path
import csv


def load_static_data(apps, schema_editor):
    energy_unit_model = apps.get_model("energy", "EnergyUnit")
    path = Path(".").resolve() / "energy" / "static" / "energy_balance"
    for csv_file in path.glob("*long_format.csv"):
        print(f"uploading {csv_file.stem}...")
        entries = []
        with open(csv_file, "r") as file:
            reader = csv.reader(file)
            headers = next(reader)
            for row in reader:
                row = {k.lower(): v for k, v in zip(headers, row)}
                _ = row.pop(""), row.pop("region"), row.pop("municipality")
                row["province_id"] = "PV28"
                entries.append(energy_unit_model(**row))

        energy_unit_model.objects.bulk_create(entries)


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0003_alter_energyunit_value"),
    ]

    operations = [
        RunPython(load_static_data),
    ]
