# Generated by Django 4.2.10 on 2024-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0004_load_csvs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyunit",
            name="region_id",
            field=models.CharField(
                choices=[
                    ("REG01", "Holland Rijnland"),
                    ("REG02", "Midden-Holland"),
                    ("REG03", "Drechsteden"),
                    ("REG04", "Rotterdam"),
                    ("REG05", "Haaglanden"),
                    ("REG06", "Zuid-Hollandse Eilanden"),
                ],
                max_length=20,
            ),
        ),
    ]
