# Generated by Django 4.2.10 on 2024-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0005_alter_energyunit_region_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyunit",
            name="res_id",
            field=models.CharField(
                choices=[
                    ("ES17", "Alblasserwaard"),
                    ("ES23", "Rotterdam Den Haag"),
                    ("ES21", "Holland Rijnland"),
                    ("ES22", "Midden-Holland"),
                    ("ES20", "Hoeksche Waard"),
                    ("ES18", "Drechtsteden"),
                    ("ES19", "Goeree-Overflakkee"),
                ],
                default="-",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
