# Generated by Django 4.2.10 on 2024-03-19 16:13

from django.db import migrations
from django.db.migrations.operations import RunPython
import csv
from django.db.models import F, Case, When, Value


def update_res_id(apps, schema_editor):
    energy_unit_model = apps.get_model("energy", "EnergyUnit")

    # Create muncipality to res id mapping
    mapping = {}
    with open("energy/static/geo_mapping.csv", "r") as file:
        reader = csv.DictReader(file)
        for row in reader:
            mapping[row["Municipality_ID"]] = row["RES_ID"]

    #  Update res_id with case/when
    whens = [
        When(municipality_id=municipality_value, then=Value(res_value))
        for municipality_value, res_value in mapping.items()
    ]
    energy_unit_model.objects.update(res_id=Case(*whens, default=F("municipality_id")))


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0006_energyunit_res_id"),
    ]

    operations = [
        RunPython(update_res_id),
    ]
