# Generated by Django 4.2.11 on 2024-10-24 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0007_energyunit_update_res_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnergyUnit",
        ),
    ]
