# Generated by Django 4.2.10 on 2024-02-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutureVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("scenario", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("json_data", models.JSONField()),
                ("geo_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
    ]
