# Generated by Django 4.2.10 on 2024-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futurevision", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futurevision",
            name="geo_id",
            field=models.CharField(
                choices=[
                    ("PV28", "Zuid-Holland"),
                    ("REG01", "Holland Rijnland"),
                    ("REG02", "Midden-Holland"),
                    ("REG03", "Drechsteden"),
                    ("REG04", "Rotterdam"),
                    ("REG05", "Haaglanden"),
                    ("REG06", "Zuid-Hollandse Eilanden"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="futurevision",
            name="scenario",
            field=models.CharField(
                choices=[
                    ("ii3050_int_nl2019_cy2012_2040", "Internationaal 2040"),
                    ("ii3050_eur_nl2019_cy2012_2040", "Europees 2040"),
                    ("ii3050_nat_nl2019_cy2012_2040", "Nationaal 2040"),
                    ("ii3050_dec_nl2019_cy2012_2040", "Decentraal 2040"),
                    ("ii3050_int_nl2019_cy2012_2050", "Internationaal 2050"),
                    ("ii3050_eur_nl2019_cy2012_2050", "Europees 2050"),
                    ("ii3050_nat_nl2019_cy2012_2050", "Nationaal 2050"),
                    ("ii3050_dec_nl2019_cy2012_2050", "Decentraal 2050"),
                ],
                max_length=100,
            ),
        ),
    ]
