# Generated by Django 4.2.11 on 2024-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futurevision", "0002_alter_futurevision_geo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futurevision",
            name="scenario",
            field=models.CharField(max_length=255),
        ),
    ]
