# Generated by Django 4.2.16 on 2025-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futurevision", "0003_alter_futurevision_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futurevision",
            name="geo_id",
            field=models.CharField(
                choices=[
                    ("PV27", "Noord-Holland"),
                    ("PV28", "Zuid-Holland"),
                    ("REG01", "Holland Rijnland"),
                    ("REG02", "Midden-Holland"),
                    ("REG03", "Drechsteden"),
                    ("REG04", "Rotterdam"),
                    ("REG05", "Haaglanden"),
                    ("REG06", "Zuid-Hollandse Eilanden"),
                    ("ET1501", "Kop van Noord-Holland"),
                    ("ET1502", "Regio Alkmaar"),
                    ("ET1503", "West-Friesland"),
                    ("ET1601", "Amsterdam"),
                    ("ET1602", "IJmond-Zuid-Kennemerland"),
                    ("ET1603", "Zaanstreek-Waterland"),
                    ("ET1604", "Gooi en Vechtstreek"),
                    ("ET1605", "Haarlemmermeer"),
                    ("ET1606", "Amstelland"),
                ],
                max_length=255,
            ),
        ),
    ]
