# Generated by Django 4.2.27 on 2026-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
