# Generated by Django 4.2.6 on 2024-02-01 09:02

from django.db import migrations
import main.blocks.image_chooser_block
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="scenarios",
            field=wagtail.fields.StreamField(
                [
                    (
                        "scenario",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "scenarios",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "scenario",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Geef meer informatie over het scenario.",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            main.blocks.image_chooser_block.ImageChooserBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                    ],
                                                    required=True,
                                                ),
                                            )
                                        ],
                                        help_text="Voeg een of meerdere scenario's toe aan de pagina.",
                                        min_num=1,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Scenarios",
            ),
        ),
    ]
