# Generated by Django 4.2.27 on 2026-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_workboarditems_type_size_mw_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workboarditems",
            name="acm_prio",
            field=models.IntegerField(
                choices=[
                    (0, "Geen prio"),
                    (1, "Categorie 1: Congestieverzachters"),
                    (2, "Categorie 2: Veiligheid"),
                    (3, "Categorie 3: Basisbehoeften"),
                ],
                default=0,
                verbose_name="ACM prioriteringskader",
            ),
        ),
        migrations.AlterField(
            model_name="workboarditems",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Idee (Zacht)"),
                    (2, "Beleidsvoornemen (Zacht)"),
                    (3, "Planvorming (Zacht)"),
                    (4, "Besluitvorming loopt (Vast)"),
                    (5, "Vastgesteld / in uitvoering (Vast)"),
                ],
                default=1,
            ),
        ),
    ]
