# Generated by Django 4.2.27 on 2026-09-11 12:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("main", "0008_alter_workboarditems_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "title_label",
                    models.CharField(
                        blank=True,
                        help_text="title above the input fields, max 255 characters",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "username_label",
                    models.CharField(
                        help_text="The placeholder and label text for the username input, max 255 characters",
                        max_length=255,
                    ),
                ),
                (
                    "password_label",
                    models.CharField(
                        help_text="The placeholder and label text for the password input, max 255 characters",
                        max_length=255,
                    ),
                ),
                (
                    "button_login_text",
                    models.CharField(
                        default="Login",
                        help_text="The text for the login button, max 255 characters",
                        max_length=255,
                    ),
                ),
                (
                    "invalid_login",
                    models.CharField(
                        default="Invalid login",
                        help_text="The text shown when the user enters wrong credentials",
                        max_length=255,
                    ),
                ),
                (
                    "redirect_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to redirect to after successful login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
    ]
